Skip to content
Navigation Menu
jsalinas1616
/
hackathon

Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Deploy to S3
Merge branch 'main' of github.com:jsalinas1616/hackathon #4
Jobs
Run details
Workflow file for this run
.github/workflows/deploy.yml at 4e52c75
name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  # Actualiza a v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Actualiza a v3
        with:
          node-version: '21.6.1'  # Usar Node.js 21.6.1

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'  
        run: |
          npm install -g aws-cli
          aws s3 sync dist/ s3://hackaton-vinneren2024 --delete
Merge branch 'main' of github.com:jsalinas1616/hackathon · jsalinas1616/hackathon@4e52c75
