name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.19'  # Asegúrate de que esta es la versión que deseas usar

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: CI=false npm run build
        # Esto previene que las advertencias sean tratadas como errores.

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-1'  
        run: |
          npm install -g aws-cli
          aws s3 sync build/ s3://hackathon-admin --delete
